name: Execute Remote Jobs

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  execute-job:
    name: ğŸš€ Execute Scrape Articles
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: denoland/setup-deno@v1

      - name: ğŸš€ Execute
        env:
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          deno run --allow-all scraper/main.ts
