name: Execute Remote Jobs

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  scrape-itman-articles:
    name: üöÄ Execute Scrape Itman Articles
    runs-on: ubuntu-latest
    steps:
      - name: üõë Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ‚¨áÔ∏è REST API with curl
        with:
          token: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          url: ${{ secrets.SUPABASE_URL }}
        run: |
          curl \
          --request POST \
          --header 'Content-Type: application/json' \
          --header "Authorization: Bearer $token" \
          --data '{"job":"scrape_itman_articles"}' \
          $url

