name: Execute Remote Jobs

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  scrape-itman-articles:
    name: ðŸš€ Execute Scrape Itman Articles
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ REST API with curl
        run: >
          curl 
          --request POST 
          --header 'Content-Type: application/json' 
          --header 'Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}' 
          --data '{"job":"scrape_itman_articles"}' 
          '${{ secrets.SUPABASE_URL }}'

